export const EFFECTS = {
  FROM_TO: "fromTo",
  GLOBAL_FROM_TO: "globalFromTo",
};

export const GLOBAL_UPDATABLES = {
  CAMERA_INSTANCE: "camera.instance",
};

export const INSTANCE_NAMES = {
  JIMBO_INTRO_TITLE: "JIMBO_INTRO_TITLE",
  LIGHT_1: "LIGHT_1",
  // LIGHT_2: "LIGHT_2",
  CAMERA: "CAMERA",
  GLOBE: "GLOBE",
  BACKGROUND: "BACKGROUND",
  FLAG: "FLAG",
  SECTION_A_PHRASE_1: "SECTION_A_PHRASE_1",
  SECTION_A_PHRASE_2: "SECTION_A_PHRASE_2",
  SECTION_A_PHRASE_3: "SECTION_A_PHRASE_3",
  SECTION_A_PHRASE_4: "SECTION_A_PHRASE_4",
  SECTION_A_PHRASE_5: "SECTION_A_PHRASE_5",
  SECTION_A_PHRASE_6: "SECTION_A__PHRASE_6",
  SECTION_A_PHRASE_7: "SECTION_A__PHRASE_7",
  SECTION_A_AD_LIBS_FOR_YOU_A: "SECTION_A_AD_LIBS_FOR_YOU_A",
  SECTION_A_AD_LIBS_FOR_YOU_B: "SECTION_A_AD_LIBS_FOR_YOU_B",
  SECTION_B_PHRASE_1: "SECTION_B_PHRASE_1",
  SECTION_B_PHRASE_2: "SECTION_B_PHRASE_2",
  BACKGROUND_SKIN_1: "BACKGROUND_SKIN_1",
  BACKGROUND_SKIN_2: "BACKGROUND_SKIN_2",
  CROSS: "CROSS",
  WITHERBERRY_LOGO: "WITHERBERRY_LOGO",
  LINE_1: "LINE_1",
  LINE_2: "LINE_2",

  // The Richest Man In Babylon
  THE_FIVE_LAWS_OF_GOLD: "THE_FIVE_LAWS_OF_GOLD",

  AMBIENT_LIGHT: "AMBIENT_LIGHT",
  DIRECTIONAL_LIGHT_1: "DIRECTIONAL_LIGHT_1",
  BACKGROUND_WALL: "BACKGROUND_WALL",
  ONE: "ONE",
  TWO: "TWO",
  THREE: "THREE",
  FOUR: "FOUR",
  FIVE: "FIVE",

  INTRO: "INTRO",
  SCENE_ONE: "SCENE_ONE",
  SCENE_TWO: "SCENE_TWO",
  SCENE_THREE: "SCENE_THREE",
  SCENE_FOUR: "SCENE_FOUR",
  SCENE_FIVE: "SCENE_FIVE",
  OUTRO: "OUTRO",

  PART_1_OF_LAW_1: "PART_1_OF_LAW_1",
  PART_2_OF_LAW_1: "PART_2_OF_LAW_1",
  PART_3_OF_LAW_1: "PART_3_OF_LAW_1",

  PART_1_OF_LAW_2: "PART_1_OF_LAW_2",
  PART_2_OF_LAW_2: "PART_2_OF_LAW_2",
  PART_3_OF_LAW_2: "PART_3_OF_LAW_2",

  PART_1_OF_LAW_3: "PART_1_OF_LAW_3",
  PART_2_OF_LAW_3: "PART_2_OF_LAW_3",
  PART_3_OF_LAW_3: "PART_3_OF_LAW_3",

  PART_1_OF_LAW_4: "PART_1_OF_LAW_4",
  PART_2_OF_LAW_4: "PART_2_OF_LAW_4",
  PART_3_OF_LAW_4: "PART_3_OF_LAW_4",

  PART_1_OF_LAW_5: "PART_1_OF_LAW_5",
  PART_2_OF_LAW_5: "PART_2_OF_LAW_5",
  PART_3_OF_LAW_5: "PART_3_OF_LAW_5",

  FROM: "FROM",
  BY: "BY",
  PART_1_OF_OUTRO: "PART_1_OF_OUTRO",
  PART_2_OF_OUTRO: "PART_2_OF_OUTRO",
  PART_3_OF_OUTRO: "PART_3_OF_OUTRO",
};
